### ISSUE TITLE
What is the correspondence between functional and structural data?

### ISSUE THREAD

**Issue by steanze** [psychoinformatics-de/studyforrest-data-phase2#10]
I found the structurals from phase 1 here: http://psydata.ovgu.de/studyforrest/structural/
I wanted to double check whether the subject IDs stayed the same (sub01 in phase 1 is sub01 in phase 2, and so on). If not, could you provide a mapping between functional data in phase 2 and structurals in phase 1? Thanks!

**Comment by mih** [comment]
Sorry for the ridiculous response latency. Yes, the mapping is the same: sub-01 is sub001.
