### ISSUE TITLE
Version of movie/audio stream

### ISSUE THREAD

**Issue by ngohgia** [psychoinformatics-de/studyforrest-data-phase2#14]
Thank you so much for making this dataset public! I see in `code/stimulus/movie/mk_movie_stimulus.sh` that two input files are needed, namely `forrest_gump_bluray_orig.mkv` and `forrest_gump_ger_stereo.flac`. May I know which distribution of the Forrest Gump movie should I obtain that corresponds to the annotation?

**Comment by jaidevshriram** [comment]
Hey!

Were you able to find the answer to your question? Facing the same issue right now as well.

**Comment by ngohgia** [comment]
My collaborator ot a copy of the files after emailing the authors directly :)
