### ISSUE TITLE
Stimulation type of the retmap runs isn't specified

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/studyforrest-data-phase2#4]
Not sure where to put this best. We have expanding/contracting rings, and clockwise/counter-clockwise wedges. Each run with several cycles if the same stimulus, but only a single stimulus type per run.

It could go into an events.tsv file, but it is not really an event...

**Comment by ayansengupta** [comment]
This should be in the sessions.tsv file. It should have the session_id and then a description of the runs in the  session.

**Comment by mih** [comment]
Coding this info in the sessions.tsv would mean that we handcraft a variable for "ses-localizer" (single row in this file) that encodes the order of stimuli wrt runs for the retmapping runs. While this is doable, I doubt that it would end up being somewhat uniform across other potential datasets with such data, and hence aid automatic discovery and analysis. So if we do this, adding a reference in BIDS for this case would make sense in order to promote uniformity -- if should to ease a concrete formalization in the future.

**Comment by chrisgorgo** [comment]
If there is "only a single stimulus type per run" shouldn't those be considered separate tasks rather than runs? For example `task-rings` and `task-wedges`?

**Comment by mih** [comment]
Indeed. Thanks for the pointer!
