### ISSUE TITLE
Add stimulus image info to events.tsv

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/studyforrest-data-phase2#6]
for @tyarkoni and the greater good.

**Comment by mih** [comment]
From BIDS:

> An optional “stim_file“ column can be added to represent the location of the stimulus file (image, video, sound etc.) presented at the given onset time. There are no restrictions on the file formats of the stimuli files, but they should be stored in the /stimuli folder (under the root folder of the dataset; with optional subfolders). The values under the stim_file column correspond to a path relative to “/stimuli”. For example “images/cat03.jpg” will be translated to “/stimuli/images/cat03.jpg”.
 
> Another optional column - “trial_type“ - represents primary categorisation of each trial to identify them as instances of the experimental conditions. For example: for a response inhibition task, it could take on values "go" and "no-go" to refer to response initiation and response inhibition experimental conditions.

**Comment by mih** [comment]
@tyarkoni @adelavega Per-stimulus image events are now listed in the events.tsv files, as promised.
Example: http://psydata.ovgu.de/studyforrest/phase2/sub-01/ses-localizer/func/sub-01_ses-localizer_task-objectcategories_run-1_events.tsv

**Comment by adelavega** [comment]
Wonderful!
